name: Records Deploy

on: 
  push:
    paths:
      - '**'

defaults:
  run:
    working-directory: .

jobs:
  build:
    name: Build and Deploy Records
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
              python-version: 3.9
        - uses: s-weigand/setup-conda@v1
          with:
            activate-conda: false
        - run: |
            conda create --name pgdc python=3.9 
            conda init bash
            conda activate pgdc
            conda install -c conda-forge gdal==3.3.2
            conda install -c conda-forge pysqlite3==0.4.6
            pip install geodatacrawler
            crawl-metadata --help
