name: Records Deploy

on: 
  push:
    paths:
      - '**'

defaults:
  run:
    working-directory: .

jobs:
  build:
    name: Build and Deploy Records
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
              python-version: 3.9
        - run: |
            sudo add-apt-repository ppa:ubuntugis/ppa
            sudo apt-get update
            sudo apt-get install gdal-bin
            sudo apt-get install libgdal-dev
            ogrinfo --version
            pip install GDAL==3.4.3
            pip install geodatacrawler pycsw sqlalchemy
            export pgdc_webdav_url=http://localhost/collections/metadata:main/items
            export pgdc_canonical_url=https://github.com/pvgenuchten/data-training/tree/main/datasets/
            pwd
            ls
            ECHO "delete records"
            pycsw-admin.py delete-records --config=./pycsw.cfg -y
            ECHO "crawl records"
            crawl-metadata --dir=./datasets --mode=export --dir-out=/tmp
            ECHO "load records"
            pycsw-admin.py load-records --config=./pycsw.cfg  --path=/tmp



