name: Records Deploy

on: 
  push:
    paths:
      - '**'

defaults:
  run:
    working-directory: .

jobs:
  build:
    name: Build and Deploy Records
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
              python-version: 3.9
        - name: install dependencies
          run: |
            sudo add-apt-repository ppa:ubuntugis/ppa
            sudo apt-get update
            sudo apt-get install gdal-bin
            sudo apt-get install libgdal-dev
            ogrinfo --version
            pip install GDAL==3.4.3
            pip install geodatacrawler pycsw sqlalchemy
        - name: configure run
          run: |
            export pgdc_webdav_url=http://localhost/collections/metadata:main/items
            export pgdc_canonical_url=https://github.com/pvgenuchten/data-training/tree/main/datasets/
            crawl-metadata --dir=./datasets --mode=export --dir-out=/tmp
        - name: publish records
          run: |
            pycsw-admin.py -c=delete-records -f=./pycsw.cfg -y
            pycsw-admin.py -c=load-records -f=./pycsw.cfg -p=/tmp



